#! /usr/bin/bash
#
#  Get the last geometry from a Gaussian log file
#    and put in .xyz file.
#  

let "l=$2+2"
grep --text -A $l " Coordinates " $1 | tail -n $2 | awk '{print $2,$4,$5,$6}' > ${1}.xyz


